Commit review fixes and fix clippy warnings
F3Joule/subsocial-v2 pull request #2
Opened 2020-03-23 13:59 UTC by F3Joule

2020-03-23 21:16 UTC, F3Joule commented
![](https://github.trello.services/images/mini-trello-icon.png) [Rename `Change` to `WhoAndWhen` and move it to separate pallet](https://trello.com/c/NITssrMY/457-rename-change-to-whoandwhen-and-move-it-to-separate-pallet)

2020-04-01 20:25 UTC, siman requested changes

2020-04-01 20:25 UTC, siman commented on runtime/src/lib.rs
>    pub const MaxSpaceOwners: u16 = u16::max_value();
I just realized that `65536` space owners could be too much 😅 .
```suggestion
  pub const MaxSpaceOwners: u16 = 1000;
```

2020-04-01 20:25 UTC, siman commented on pallets/space-owners/src/functions.rs
> +  pub fn change_change_from_pending_to_executed(space_id: SpaceId, change_id: ChangeId) -> DispatchResult {
```suggestion
  pub fn move_change_from_pending_state_to_executed(space_id: SpaceId, change_id: ChangeId) -> DispatchResult {
```

2020-04-01 20:25 UTC, siman commented on pallets/space-owners/src/functions.rs
> +    Self::change_change_from_pending_to_executed(space_id, change_id)?;
```suggestion
    Self::move_change_from_pending_state_to_executed(space_id, change_id)?;
```

2020-04-01 20:25 UTC, siman commented on pallets/space-owners/src/functions.rs
> +    if (block_number % T::CleanExpiredChangesPeriod::get()).is_zero() {
```suggestion
    if (block_number % T::DeleteExpiredChangesPeriod::get()).is_zero() {
```

2020-04-01 20:25 UTC, siman commented on pallets/space-owners/src/lib.rs
> +  type CleanExpiredChangesPeriod: Get<Self::BlockNumber>;
```suggestion
  type DeleteExpiredChangesPeriod: Get<Self::BlockNumber>;
```

2020-04-01 20:25 UTC, siman commented on pallets/space-owners/src/lib.rs
> +    const CleanExpiredChangesPeriod: T::BlockNumber = T::CleanExpiredChangesPeriod::get();
```suggestion
    const DeleteExpiredChangesPeriod: T::BlockNumber = T::DeleteExpiredChangesPeriod::get();
```

2020-04-01 20:25 UTC, siman commented on pallets/space-owners/src/lib.rs
> +    /// Period in blocks to initialize cleaning of pending changes that are outdated.
```suggestion
    /// Period in blocks to initialize deleting of pending changes that are outdated.
```

2020-04-01 20:25 UTC, siman commented on pallets/space-owners/src/lib.rs
>      /// Period for which change proposal is active.
```suggestion
    /// Period in blocks for which change proposal is can remain in a pending state until deleted.
```

2020-04-01 20:25 UTC, siman commented on pallets/space-owners/src/tests.rs
> +	pub const CleanExpiredChangesPeriod: u64 = 1800;
```suggestion
	pub const DeleteExpiredChangesPeriod: u64 = 1800;
```

2020-04-01 20:25 UTC, siman commented on pallets/space-owners/src/tests.rs
> +  type CleanExpiredChangesPeriod = CleanExpiredChangesPeriod;
```suggestion
  type DeleteExpiredChangesPeriod = DeleteExpiredChangesPeriod;
```

2020-04-01 20:25 UTC, siman commented on pallets/space-owners/src/lib.rs
> +  /// Maximum change notes length.
```suggestion
  /// Maximum length of change notes.
```

2020-04-01 20:25 UTC, siman commented on pallets/space-owners/src/lib.rs
>      pub fn cancel_proposal(
```suggestion
    pub fn cancel_change(
```

2020-04-01 20:25 UTC, siman commented on pallets/space-owners/src/lib.rs
> +    /// Change was not found in a space owners
```suggestion
    /// Change was not found by id
```

2020-04-01 20:25 UTC, siman commented on pallets/space-owners/src/lib.rs
>      /// No updates proposed in change proposal
```suggestion
    /// No updates proposed with this change
```

2020-04-01 20:25 UTC, siman commented on pallets/space-owners/src/lib.rs
> +    /// There are not enough confirmations on a change
```suggestion
    /// There are not enough confirmations for this change
```

2020-04-01 20:25 UTC, siman commented on pallets/space-owners/src/lib.rs
> +    /// Change is not tied to an owed wallet
```suggestion
    /// Change is not related to this space
```

2020-04-01 20:25 UTC, siman commented on pallets/space-owners/src/lib.rs
>      NotAProposalCreator,
```suggestion
    NotAChangeCreator,
```

2020-04-01 20:25 UTC, siman commented on pallets/space-owners/src/lib.rs
> +    /// Overflow in Wallet executed change counter
```suggestion
    /// Overflow when incrementing a counter of executed changes
```

2020-04-01 20:25 UTC, siman commented on pallets/space-owners/src/lib.rs
> +    /// Underflow in Wallet pending change counter
```suggestion
    /// Underflow when decrementing a counter of executed changes
```

2020-04-01 20:25 UTC, siman commented on pallets/space-owners/src/lib.rs
> +    /// Maximum change notes length.
```suggestion
    /// Maximum length of change notes.
```

2020-04-01 20:25 UTC, siman commented on pallets/space-owners/src/lib.rs
> +  /// Period in blocks to initialize cleaning of pending changes that are outdated.
```suggestion
  /// Period in blocks for which change proposal is can remain in a pending state until deleted.
```

2020-04-02 15:18 UTC, siman approved these changes

2020-04-02 15:18 UTC, siman commented on pallets/space-owners/src/tests.rs
>  	pub const MaxSpaceOwners: u16 = u16::max_value();
```suggestion
	pub const MaxSpaceOwners: u16 = 1000;
```

2020-04-02 15:19 UTC, merged